server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/orderdb
    username: root
    password: gtavcvv0928

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer